<h1>Cadastro de produtos</h1>

<?php echo $this->form()->openTag($form); ?>
<!--<form method="post" action="\Index\Cadastrar">-->
    <div class="form-group">
        <label>Nome</label>
        <?php echo $this->formInput($form->get('nome'));
              echo $this->formElementErrors()->render($form->get('nome'));
        ?>
<!--        <input type="text" name="nome" class="form-control">-->
    </div>

    <div class="form-group">
        <label>Preço</label>
        <?php echo $this->formInput($form->get('preco')); ?>
<!--        <input type="number" name="preco" class="form-control">-->
    </div>

    <div class="form-group">
        <label>Categoria</label>
        <?php echo $this->formSelect($form->get('categoria')); ?>
    </div>

    <div class="form-group">
        <label>Descrição</label>
        <?php echo $this->formTextArea($form->get('descricao')); ?>
<!--        <textarea name="descricao" class="form-control"></textarea>-->
    </div>

    <?php
        echo $this->formRow($form->get('csrf'));
    ?>

    <div class="form-group">
        <input class="btn btn-primary" type="submit" value="Salvar">
    </div>
<!--</form>-->
<?php echo $this->form()->closeTag($form);

