<h1>Editar produto</h1>

<form method="post" action="<?= $this->url('application', ['action' => 'Editar']) ?>">
    <input type="hidden" value="<?= $produto->getId() ?>" name="id">
    <div class="form-group">
        <label>Nome</label>
        <input type="text" name="nome" class="form-control" value="<?= $produto->getNome() ?>">
    </div>

    <div class="form-group">
        <label>Preço</label>
        <input type="number" name="preco" class="form-control" value="<?= $produto->getPreco() ?>">
    </div>

    <div class="form-group">
        <label>Descrição</label>
        <textarea name="descricao" class="form-control"><?= $produto->getDescricao() ?></textarea>
    </div>

    <div class="form-group">
        <input class="btn btn-primary" type="submit" value="Salvar">
    </div>
</form>