<h1>Listagem de produtos</h1>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Preço</th>
            <th>Categoria</th>
            <th>Descrição</th>
            <th>Ações</th>
        </tr>
    </thead>
    <tbody>
        <?php
            foreach ($produtos as $prod){
        ?>
           <tr>
               <td><?= $prod->getNome(); ?></td>
               <td><?= $prod->getPreco(); ?></td>
               <td><?= $prod->getCategoria()->getNome(); ?></td>
               <td><?= $prod->getDescricao(); ?></td>
               <td><a href="<?= $this->url('application', ['action' => 'Remover', 'id' => $prod->getId()]) ?>" class="btn btn-danger">Remover</a>
                   <a href="<?= $this->url('application', ['action' => 'Editar', 'id' => $prod->getId()]) ?>" class="btn btn-info">Editar</a></td>
           </tr>
        <?php
            }
        ?>
    </tbody>
</table>

<?php echo $this->PaginationHelper($produtos, $qtdPorPagina, '/Produtos'); ?>

