<h1>Remover produto</h1>
<form method="post" action="<?= $this->url('application', ['action' => 'remover']) ?>">
    <input type="hidden" value="<?= $id; ?>" name="id">
    <p class="alert alert-danger">Deseja realmente remover esse produto da lista?</p>
    <input type="submit" value="Sim" class="btn btn-danger">
    <a href="<?= $this->url('application'); ?>" class="btn btn-primary">Não</a>
</form>