<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Sistema de estoque</title>

    <?php echo $this->headLink()
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
    ?>

    <?php echo $this->headScript()
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',));
    ?>

</head>
<body>
    <header>
        <nav class="navbar navbar-default">
            <div class="navbar-header">
                <a href="/" class="navbar-brand">Kunstee</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="<?= $this->url('application', ['action' => 'Index']) ?>">Listagem dos produtos</a></li>
                <li><a href="<?= $this->url('application', ['action' => 'Cadastrar']) ?>">Cadastro de produtos</a></li>
                <li><a href="/Usuario/Logaut">Sair</a></li>
            </ul>
        </nav>
    </header>
    <main class="conteudo">
        <?php echo $this->FlashHelper(); ?>
        <?= $this->content; ?>
    </main>
    <footer class="rodape">
        Todos os direitos reservados.
    </footer>
</body>
</html>
